### ISSUE TITLE
Unable to run a simple js file

### ISSUE THREAD

**Issue by sebastian-naicker** [facebookexperimental/rome#306]
Description:

Rome fails to execute my script file. I have tested with node, and it works fine, hence I decided to report an issue.

## Steps To Reproduce
1. Follow the installation & getting started guide on the rome docs.
2. Create a new directory
3. Run `rome init` and proceed with the recommended settings
4. create a new file, in this case I created `hello.js`
5. Insert the following content
```
// hello.js

function name(name) {
  console.log(`Hello ${name}!`)
}

name('Bob')
```

## Expected Results

Expected to print out `Hello Bob!` to the console. Instead throws an error

```
Unhandled CLI query error
/home/sebastiann/workspace/PERSONAL/rome_test/hello.js:9
___R$$priv$project$rome_test$hello_js$name('Bob');
^

ReferenceError: ___R$$priv$project$rome_test$hello_js$name is not defined
  at name (project-rome_test/hello.js:6:0)
  at global.<anonymous (/home/sebastiann/workspace/PERSONAL/rome_test/hello.js:13:2) generated source location
  at Script.runInContext (vm.js:127:19)
  at ___R$project$rome$$romejs$core$common$utils$executeMain_ts$default (project-rome/@romejs/core/common/utils/executeMain.ts:110:15)
  at Object.callback (project-rome/@romejs/core/client/commands/run.ts:61:38)
  at ___R$project$rome$$romejs$core$client$ClientRequest_ts$default.initFromLocal (project-rome/@romejs/core/client/ClientRequest.ts:72:16)
  at ___R$project$rome$$romejs$core$client$ClientRequest_ts$default.init (project-rome/@romejs/core/client/ClientRequest.ts:37:13)
  at ___R$project$rome$$romejs$core$client$Client_ts$default.query (project-rome/@romejs/core/client/Client.ts:375:16)
  at ___R$project$rome$$romejs$cli$cli_ts$default (project-rome/@romejs/cli/cli.ts:318:14)
  at ___R$project$rome$$romejs$diagnostics$wrap_ts$catchDiagnostics (project-rome/@romejs/diagnostics/wrap.ts:25:18)
```

**Comment by sebmck** [comment]
Thanks for the report! Fixed by 8be8243c0ca7d98d1b23c31190530cbd140aea80. The problem here was the function being the same name as a parameter which caused a collision in some internal data structure that was shared.
