### ISSUE TITLE
Can't Install: Missing package version

### ISSUE THREAD

**Issue by Tembocs** [facebookexperimental/rome#313]
After successful compilation, installation of Rome fails with error message ```Can't install: /rome/dist: Missing package version```

## Steps To Reproduce
1. Clone Rome repository: ```git clone https://github.com/facebookexperimental/rome```
2. Compile it: ```cd rome; ./scripts/build-release dist```
3. Try to install: ```npm install -g ./dist/```

The last step (installation) fails with error message: ```Can't install /rome/dist: Missing package version.

## Expected Results
Expected to have successful installation of Rome.

NB: Git Rome repository hash: 0f6c5d46

===========================================================================
## Full log file content:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '~/Tools/nodejs/bin/node',
1 verbose cli   '~/Tools/nodejs/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   './dist/'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose npm-session fc533649d1031f33
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly pacote directory manifest for undefined@file:dist fetched in 14ms
8 timing stage:loadCurrentTree Completed in 29ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
12 silly install loadShrinkwrap
13 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
14 silly install loadAllDepsIntoIdealTree
15 timing stage:rollbackFailedOptional Completed in 0ms
16 timing stage:runTopLevelLifecycles Completed in 32ms
17 verbose stack Error: Can't install ~/projects/javascript/rome/dist: Missing package version
17 verbose stack     at hasMinimumFields (~/Tools/nodejs/lib/node_modules/npm/lib/install/validate-args.js:28:15)
17 verbose stack     at Array.<anonymous> (~/Tools/nodejs/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
17 verbose stack     at LOOP (~/Tools/nodejs/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
17 verbose stack     at chain (~/Tools/nodejs/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
17 verbose stack     at ~/Tools/nodejs/lib/node_modules/npm/lib/install/validate-args.js:16:5
17 verbose stack     at ~/Tools/nodejs/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
17 verbose stack     at Array.forEach (<anonymous>)
17 verbose stack     at ~/Tools/nodejs/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
17 verbose stack     at Array.forEach (<anonymous>)
17 verbose stack     at asyncMap (~/Tools/nodejs/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
17 verbose stack     at module.exports (~/Tools/nodejs/lib/node_modules/npm/lib/install/validate-args.js:15:3)
17 verbose stack     at Array.<anonymous> (~/Tools/nodejs/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
17 verbose stack     at LOOP (~/Tools/nodejs/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
17 verbose stack     at chain (~/Tools/nodejs/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
17 verbose stack     at Installer.loadAllDepsIntoIdealTree (~/Tools/nodejs/lib/node_modules/npm/lib/install.js:483:3)
17 verbose stack     at Array.<anonymous> (~/Tools/nodejs/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
18 verbose cwd ~/projects/javascript/rome
19 verbose Linux 5.4.0-26-generic
20 verbose argv "~/Tools/nodejs/bin/node" "~/Tools/nodejs/bin/npm" "install" "-g" "./dist/"
21 verbose node v12.16.2
22 verbose npm  v6.14.4
23 error Can't install ~/projects/javascript/rome/dist: Missing package version
24 verbose exit [ 1, true ]
```

**Comment by Tembocs** [comment]
After compilation, adding "version" field to ```~/projects/javascript/rome/dist/package.json``` with any version number as its value makes the installation successful without any error. I could not figure out where this files comes from during compilation.
