### ISSUE TITLE
yarn dev-rome not workin on linux (Ubuntu with zsh)

### ISSUE THREAD

**Issue by langpavel** [facebookexperimental/rome#328]
## Steps To Reproduce

Linux, zsh
```
$ node ./scripts/dev-rome
 Building trunk 
Unhandled CLI query error
TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
  at Object.watch (fs.js:1441:10)
  at ___R$project$rome$$romejs$fs$index_ts$watch (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:64308:58) generated source location
  at Object.onFoundDirectory (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:89123:24) generated source location
  at ___R$project$rome$$romejs$core$master$fs$MemoryFileSystem_ts$default.addDirectory (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:90062:13) generated source location
  at ___R$$priv$project$rome$$romejs$core$master$fs$MemoryFileSystem_ts$createRegularWatcher (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:89187:21) generated source location
  at ___R$project$rome$$romejs$core$master$fs$MemoryFileSystem_ts$default.watch (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:89705:27) generated source location
  at ___R$project$rome$$romejs$core$master$project$ProjectManager_ts$default.addProjectWithConfig (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:79360:6) generated source location
  at ___R$project$rome$$romejs$core$master$project$ProjectManager_ts$default.init (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:78854:6) generated source location
  at ___R$project$rome$$romejs$core$master$Master_ts$default.init (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:96493:6) generated source location
  at ___R$project$rome$$romejs$core$client$Client_ts$default.findOrStartMaster (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:97893:6) generated source location
  at ___R$project$rome$$romejs$core$client$ClientRequest_ts$default.initFromMaster (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:76728:23) generated source location
  at ___R$project$rome$$romejs$core$client$ClientRequest_ts$default.init (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:76659:15) generated source location
  at ___R$project$rome$$romejs$core$client$Client_ts$default.query (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:97794:18) generated source location
  at ___R$project$rome$$romejs$cli$cli_ts$default (/home/langpavel/Projects/work/rome/rome/scripts/vendor/rome.cjs:101099:16) generated source location
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sebmck** [comment]
Node version?

**Comment by sebmck** [comment]
I guess it doesn't matter. I'm on Linux running Node v12.6.0 and have never encountered this. Closed commit should fix this. Thanks for the report!

**Comment by langpavel** [comment]
I'm on node 14.0.0

**Comment by ivan** [comment]
I tried master 432b9ced876684c102724aedb707909ed2d32312 and see this on NixOS, maybe the vendored rome needs to be updated?

```
# node --version
v14.2.0

# node ./scripts/dev-rome --help
 Building trunk
Unhandled CLI query error
TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
  at Object.watch (fs.js:1441:10)
  at ___R$project$rome$$romejs$fs$index_ts$watch (/home/at/code/js/rome/scripts/vendor/rome.cjs:64308:58) generated source location
  at Object.onFoundDirectory (/home/at/code/js/rome/scripts/vendor/rome.cjs:89123:24) generated source location
  at ___R$project$rome$$romejs$core$master$fs$MemoryFileSystem_ts$default.addDirectory (/home/at/code/js/rome/scripts/vendor/rome.cjs:90062:13) generated source location
  at ___R$$priv$project$rome$$romejs$core$master$fs$MemoryFileSystem_ts$createRegularWatcher (/home/at/code/js/rome/scripts/vendor/rome.cjs:89187:21) generated source location
  at ___R$project$rome$$romejs$core$master$fs$MemoryFileSystem_ts$default.watch (/home/at/code/js/rome/scripts/vendor/rome.cjs:89705:27) generated source location
  at ___R$project$rome$$romejs$core$master$project$ProjectManager_ts$default.addProjectWithConfig (/home/at/code/js/rome/scripts/vendor/rome.cjs:79360:6) generated source location
  at ___R$project$rome$$romejs$core$master$project$ProjectManager_ts$default.init (/home/at/code/js/rome/scripts/vendor/rome.cjs:78854:6) generated source location
  at ___R$project$rome$$romejs$core$master$Master_ts$default.init (/home/at/code/js/rome/scripts/vendor/rome.cjs:96493:6) generated source location
  at ___R$project$rome$$romejs$core$client$Client_ts$default.findOrStartMaster (/home/at/code/js/rome/scripts/vendor/rome.cjs:97893:6) generated source location
  at ___R$project$rome$$romejs$core$client$ClientRequest_ts$default.initFromMaster (/home/at/code/js/rome/scripts/vendor/rome.cjs:76728:23) generated source location
  at ___R$project$rome$$romejs$core$client$ClientRequest_ts$default.init (/home/at/code/js/rome/scripts/vendor/rome.cjs:76659:15) generated source location
  at ___R$project$rome$$romejs$core$client$Client_ts$default.query (/home/at/code/js/rome/scripts/vendor/rome.cjs:97794:18) generated source location
  at ___R$project$rome$$romejs$cli$cli_ts$default (/home/at/code/js/rome/scripts/vendor/rome.cjs:101099:16) generated source location
```

My git tree is clean, I did `git reset --hard` and `git clean -xdf`

**Comment by sebmck** [comment]
@ivan What is `process.platform` on NixOS?

**Comment by ivan** [comment]
```
# node
Welcome to Node.js v14.2.0.
Type ".help" for more information.
> process.platform
'linux'
```

**Comment by SolarLiner** [comment]
`./scripts/dev-rome` works with Node.js 13, but not Node.js 14 (tested on Ubuntu 20.04); so this is related to the new version of Node.js.

**Comment by sebmck** [comment]
I made the relevant fix to set `recursive` to `false` under Linux which was the commit that closed this issue 51d9a93489db72e11c20f124afdf7cb311b9c6fa.

From what I can tell all Node is doing it should only error when it's `true` which I don't think is possible? [`fs.js`](https://github.com/nodejs/node/blob/b533fb3508009e5f567cc776daba8fbf665386a6/lib/fs.js#L1440)

I'm not really sure why it would still be triggered.

**Comment by ivan** [comment]
@sebmck `scripts/vendor/rome.cjs` wasn't updated, it still has the old

```
        if (process.platform === 'linux') {
          // Node on Linux doesn't support recursive directory watching so we need an fs.watch for every directory...
        } else if (!folderPath.equal(projectFolderPath)) {
```

**Comment by sebmck** [comment]
Ahhh right that'd do it...

**Comment by sebmck** [comment]
#471 should fix it. Thanks @ivan for the catch!
