### ISSUE TITLE
setup breaks when node < 6

### ISSUE THREAD

**Issue by binarybaba** [facebookexperimental/rome#372]
Description:
`_setup.cjs` throws a syntax error when we're using node v6 or lesser. It made sense for me to file an issue here since node is giving an LTS support for 8x,6x and 4x.
```
➜ nvm use 4            
Now using node v4.9.1 (npm v2.15.11)

rome on  master is 📦 v0.0.2 via ⬢ v4.9.1 
➜ scripts/dev-rome test
/Users/amin/dev/rome/scripts/dev-rome:12
const {argv} = require('./_constants.cjs');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

rome on  master is 📦 v0.0.2 via ⬢ v4.9.1 
➜ nvm use 6            
Now using node v6.14.3 (npm v3.10.10)

rome on  master is 📦 v0.0.2 via ⬢ v6.14.3 took 2s 
➜ scripts/dev-rome test
/Users/amin/dev/rome/scripts/_setup.cjs:22
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/amin/dev/rome/scripts/dev-rome:10:1)

rome on  master is 📦 v0.0.2 via ⬢ v6.14.3 
➜ nvm use 8            
Now using node v8.17.0 (npm v6.13.4)

rome on  master is 📦 v0.0.2 via ⬢ v8.17.0 
➜ scripts/dev-rome test
Rome requires Node >=v12 but got v8.17.0
```

## Steps To Reproduce

Switch to node versions <=6 and run `scripts/dev-rome test` 

## Expected Results
Should say `Rome requires Node >=v12 but got <xxx>`

**Comment by binarybaba** [comment]
I'll pick this up and send a PR

**Comment by ljharb** [comment]
6 is EOL, as is 8; the only node versions currently in LTS are 10 and 12.

**Comment by binarybaba** [comment]
I know. I just think it should exit nicely rather than give out a stack trace. What do you think? I mean this is ultra low priority

**Comment by binarybaba** [comment]
I was looking at the docs and it did say it was in LTS so I kinda got confused :D

**Comment by sebmck** [comment]
We do have a check that you're running Node >12 which is the only version currently supported for development. There's isn't anything we can really do about Node versions so old that they don't support basic ES2015 syntax.
